class Zoneminder < Formula
  desc "Video surveillance and security camera system"
  homepage "https://zoneminder.com"
  license "GPL-2.0-or-later"
  head "https://github.com/ZoneMinder/zoneminder.git", branch: "master"

  # No stable spec yet. The macOS build fixes are on master and are not in
  # 1.38.4, so a formula pointing at the current release would not compile.
  # A url/sha256 pair goes here once a release carries them.

  depends_on "cmake" => :build
  depends_on "pkgconf" => :build
  depends_on "ffmpeg"
  depends_on "gsoap"
  depends_on "jpeg-turbo"
  depends_on "mosquitto"
  depends_on "mysql-client"
  depends_on "nlohmann-json"
  depends_on "openssl@3"
  depends_on "pcre2"
  depends_on "perl"

  def install
    mysql = Formula["mysql-client"]

    # Everything that outlives an upgrade is pinned outside the cellar. The
    # build's own macOS defaults derive from the install prefix, which here is a
    # versioned cellar directory, so config and state would be thrown away on
    # every upgrade if they were left alone.
    args = %W[
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_MAN=0
      -DZM_CONFIG_DIR=#{etc}/zm
      -DZM_CONFIG_SUBDIR=#{etc}/zm/conf.d
      -DZM_RUNDIR=#{var}/run/zm
      -DZM_SOCKDIR=#{var}/run/zm
      -DZM_PATH_MAP=#{var}/run/zm
      -DZM_LOGDIR=#{var}/log/zm
      -DZM_CACHEDIR=#{var}/cache/zoneminder
      -DZM_TMPDIR=#{var}/cache/zoneminder/temp
      -DZM_CONTENTDIR=#{var}/lib/zoneminder
      -DZM_DIR_EVENTS=#{var}/lib/zoneminder/events
      -DPERL_EXECUTABLE=#{formula_opt_bin("perl")}/perl
      -DZM_PERL_INSTALL_PATH=#{libexec}/lib/perl5
      -DZM_PERL_SEARCH_PATH=#{libexec}/lib/perl5
      -DOPENSSL_ROOT_DIR=#{formula_opt_prefix("openssl@3")}
      -DCMAKE_PREFIX_PATH=#{mysql.opt_prefix};#{HOMEBREW_PREFIX}
      -DCMAKE_C_FLAGS=-I#{mysql.opt_include}
      -DCMAKE_CXX_FLAGS=-I#{mysql.opt_include}
    ]

    # mysql-client is keg-only, so its headers are not on the default include
    # path and the bare find_library call in CMakeLists.txt misses them. Without
    # the flags above the build stops at "'mysql/mysql.h' file not found".

    system "cmake", "-S", ".", "-B", "build", *args, *std_cmake_args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"

    # Generated by the build with these paths already substituted. Kept in the
    # keg rather than loaded, because /Library/LaunchDaemons is read at boot and
    # that is the admin's decision to make.
    (prefix/"com.zoneminder.zoneminder.plist").write \
      (buildpath/"build/misc/com.zoneminder.zoneminder.plist").read

    # Sample web server configuration, likewise generated and likewise guidance
    # rather than something to drop in unread.
    (share/"zoneminder/misc").install \
      (buildpath/"build/misc/apache.conf"),
      (buildpath/"build/misc/nginx.conf")
  end

  def post_install
    [
      var/"run/zm",
      var/"log/zm",
      var/"cache/zoneminder/temp",
      var/"lib/zoneminder/events",
    ].each(&:mkpath)
  end

  def caveats
    <<~EOS
      ZoneMinder is not usable straight out of the box. Three things are left,
      and none of them can safely be done for you.

      1. Perl modules. These are not bundled and the build only warns when they
         are missing, so it is easy to end up with a working install whose Perl
         daemons cannot read monitor state at all:

           cpanm --notest Sys::Mmap Date::Manip DBI LWP::UserAgent

         DBD::MariaDB needs its link flags spelled out, because mysql_config
         asks for -lzstd -lssl -lcrypto and a Homebrew Perl carries no -L for
         the Homebrew prefix:

           cpanm --notest \\
             --configure-args="--libs=\\"-L#{formula_opt_lib("mysql-client")} -L#{HOMEBREW_PREFIX}/lib -lmysqlclient -lz -lzstd -lssl -lcrypto -lresolv\\" --cflags=\\"-I#{formula_opt_include("mysql-client")}/mysql\\"" \\
             DBD::MariaDB

      2. A database:

           brew services start mariadb
           mysql -u root < #{share}/zoneminder/db/zm_create.sql
           mysql -u root -e "CREATE USER IF NOT EXISTS 'zmuser'@localhost IDENTIFIED BY 'zmpass';"
           mysql -u root -e "GRANT LOCK TABLES, ALTER, SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX ON zm.* TO 'zmuser'@localhost;"
           zmupdate.pl --nointeractive

         Change those credentials here and in #{etc}/zm/zm.conf before putting
         this anywhere reachable.

      3. A web server. Samples for Apache and nginx, with your paths already
         filled in, are at #{share}/zoneminder/misc.

      Then start it:

           zmpkg.pl start

      To start at boot, note that `brew services` cannot run ZoneMinder: it
      forks and returns, and the generated launchd job needs AbandonProcessGroup
      to stop launchd killing everything when it does, which the services DSL
      cannot express. Load the job directly instead:

           sudo install -o root -g wheel -m 644 \\
             #{prefix}/com.zoneminder.zoneminder.plist /Library/LaunchDaemons/
           sudo launchctl load -w /Library/LaunchDaemons/com.zoneminder.zoneminder.plist

      Unloading does not stop ZoneMinder; run `zmpkg.pl stop` first.
    EOS
  end

  test do
    # zmc prints the bare version and nothing else. Not zmu --version, which is
    # the Video4Linux API version to query with, and which prints the usage
    # screen and exits 0 whatever you give it.
    assert_match(/^\d+\.\d+\.\d+/, shell_output("#{bin}/zmc --version"))

    # Perl modules went where ZM_PERL_INSTALL_PATH put them rather than into
    # the Perl keg, which is the part most likely to drift on an upgrade.
    assert_path_exists libexec/"lib/perl5/ZoneMinder.pm"

    # The paths that have to outlive an upgrade really are outside the cellar.
    assert_path_exists etc/"zm/zm.conf"
    refute_match prefix.to_s, (etc/"zm/conf.d/01-system-paths.conf").read
  end
end
